# tables from dogepartyd.9.db schema

tables = ("balances",
"bet_expirations",
"bet_match_expirations",
"bet_match_resolutions",
"bet_matches",
"bets",
"blocks",
"broadcasts",
"btcpays",
"burns",
"callbacks",
"cancels",
"credits",
"debits",
"dividends",
"issuances",
"mempool",
"messages",
"order_expirations",
"order_match_expirations",
"order_matches",
"orders",
"rps",
"rps_expirations",
"rps_match_expirations",
"rps_matches",
"rpsresolves",
"sends",
"transactions")
